// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuzmN2BJgPubD0dzmLiSPMc1xOWtddx0',
    appId: '1:353051682231:android:b1fee944dcfb06608cb432',
    messagingSenderId: '353051682231',
    projectId: 'p24ecommerce',
    storageBucket: 'p24ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaYg8YPzffokskioxA4DgMY_PPx34YxY',
    appId: '1:353051682231:ios:e8b8c756ff3456fc8cb432',
    messagingSenderId: '353051682231',
    projectId: 'p24ecommerce',
    storageBucket: 'p24ecommerce.appspot.com',
    androidClientId: '353051682231-0pe73kq45as6r26lg7eqefstfu7v2mda.apps.googleusercontent.com',
    iosClientId: '353051682231-rchertolq28cu3hs43fkdjksq88p8cho.apps.googleusercontent.com',
    iosBundleId: 'io.izisoft.p24ecommerce',
  );
}
