// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9b6dQVXVXyKEBpVfHj5FgnMIA67N3PFk',
    appId: '1:1015886942893:android:e1c1d0c38e1b6779a9ac24',
    messagingSenderId: '1015886942893',
    projectId: 'supertransport-80388',
    storageBucket: 'supertransport-80388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJJJd87gm7--CWdxpSe0MjdRNSCuzrm5A',
    appId: '1:1015886942893:ios:af8adaa81bea5a5ca9ac24',
    messagingSenderId: '1015886942893',
    projectId: 'supertransport-80388',
    storageBucket: 'supertransport-80388.appspot.com',
    androidClientId: '1015886942893-9u3pak70h6a1i8boqm86i79guftbp118.apps.googleusercontent.com',
    iosClientId: '1015886942893-h4kl5c8255e11kbp64169ea80oqnp5lk.apps.googleusercontent.com',
    iosBundleId: 'io.izisoft.p22supertransport',
  );
}
