// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjSL4yBnXapdGci6_iUN6cr4ylMToEec',
    appId: '1:992101836378:web:dacb6aff8ef2d251b19a63',
    messagingSenderId: '992101836378',
    projectId: 'p21haqua-2173a',
    authDomain: 'p21haqua-2173a.firebaseapp.com',
    storageBucket: 'p21haqua-2173a.appspot.com',
    measurementId: 'G-LEBL75M3PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1m3ncalw3fm9QkyLnp-I6yeOrdaaulS8',
    appId: '1:992101836378:android:647069fbe7207e82b19a63',
    messagingSenderId: '992101836378',
    projectId: 'p21haqua-2173a',
    storageBucket: 'p21haqua-2173a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexmC1zKBJHDtVsQKZd9dAqb4BCEg0mNQ',
    appId: '1:992101836378:ios:d0f078c97a0fffa8b19a63',
    messagingSenderId: '992101836378',
    projectId: 'p21haqua-2173a',
    storageBucket: 'p21haqua-2173a.appspot.com',
    androidClientId: '992101836378-8ntnck475u8stbl5ntfn6lphgveaen1t.apps.googleusercontent.com',
    iosClientId: '992101836378-43in63t7b7la7focaspuqr96t977n4l2.apps.googleusercontent.com',
    iosBundleId: 'io.izisoft.p021haquaa.ImageNotification',
  );
}
