name: template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  carousel_slider: ^4.1.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  fancy_bottom_navigation: ^0.3.3
  get_it: ^7.2.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  lint: ^1.8.2
  package_info: ^2.0.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.3
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  url_launcher: ^6.0.17
  flutter_point_tab_bar: ^0.2.0
  flutter_svg: ^1.1.1
  timeago: ^3.1.0
  flutter_easyloading: ^3.0.3
  flutter_html: ^3.0.0-alpha.5
  intl: ^0.17.0
  file_picker: ^4.1.4
  flutter_rating_bar: ^4.0.0
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^7.3.0
  html_unescape: ^2.0.0
  tiengviet: ^0.5.0
  flutter_styled_toast: ^2.0.0
  email_validator: ^2.0.1
  dropdown_search: ^5.0.2
  permission_handler: ^10.0.0
  glass_kit: ^2.0.1
  image_cropper: ^3.0.0
  local_auth: ^2.1.0
  clipboard: ^0.1.3
  share_plus: ^4.0.10
  currency_text_input_formatter: ^2.1.5
  glass: ^1.0.1+1
  flutter_masked_text2: ^0.9.1
  cached_network_image: ^3.2.0
  ticket_material: ^0.3.1
  flutter_smart_dialog: ^4.5.3+2
  timer_count_down: ^2.2.1
  confetti: ^0.7.0
  device_info: ^2.0.3
  build_runner: ^2.1.7
  animated_text_kit: ^4.2.1
  uuid: ^3.0.5
  tiktoklikescroller: ^0.2.0
  marquee: ^2.2.3
  app_settings: ^4.1.8
  speech_to_text: ^5.5.0
  avatar_glow: ^2.0.2
  bordered_text: ^2.0.0
  timeline_tile: ^2.0.0
  rich_text_controller: ^1.4.0
  firebase_core: ^1.21.0
  firebase_messaging: ^13.0.2
  flutter_local_notifications: ^9.6.1
  rxdart: ^0.27.4
  google_sign_in: ^5.3.3
  the_apple_sign_in: ^1.1.1
  flutter_secure_storage: ^6.0.0
  firebase_auth: ^3.6.4
  flutter_spinkit: ^5.1.0
  image: 3.2.0
  badges: 2.0.3
  flutter_webrtc: ^0.9.7
  socket_io_client: ^2.0.0
  scroll_to_index: 3.0.1
  fluttertoast: 8.0.9
  internet_connection_checker: 0.0.1+4
  flutter_drawing_board: 0.3.1
  assets_audio_player: 3.0.5
  flutter_facebook_auth: ^3.5.7
  roundcheckbox: 2.0.5
  izi_izi_checkbox_grouped:
    path: ./izi_checkbox_grouped-1.8.1-izi
  flutter_background_service: ^2.1.3
  flutter_background_service_android: ^2.0.3
  system_alert_window: 1.1.2
  exif: 3.1.2
  google_fonts: ^3.0.1
  open_file: ^3.2.1
  audioplayers: ^1.0.0
  video_player: ^2.4.5
dev_dependencies:
  # flutter pub pub run dapackages:dapackages.dart ./pubspec.yaml
  dapackages: ^1.6.0
  change_app_package_name: ^1.0.0

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LOGO_HAQUA.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/account_image/
    - assets/language/
    - assets/icons/
    - assets/svg/
    - assets/audios/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    # - family: SFPro
    #   fonts:
    #     - asset: assets/fonts/sfpro/SF-Pro-Text-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/sfpro/SFProText-MediumItalic.ttf
    #       weight: 400
    #       style: italic
    #     - asset: assets/fonts/sfpro/SFProText-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/sfpro/SFProText-SemiBoldItalic.ttf
    #       weight: 600
    #       style: italic
    #     - asset: assets/fonts/sfpro/SFProText-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/sfpro/SFProText-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    #     - asset: assets/fonts/sfpro/SFProText-Heavy.ttf
    #       weight: 800
    #     - asset: assets/fonts/sfpro/SFProText-HeavyItalic.ttf
    #       weight: 800
