name: template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+130

environment:
  sdk: ">=2.16.2 <3.0.0"
  # sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.3.7
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  # fancy_bottom_navigation: ^0.3.3
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  # flutter_html: ^2.1.1
  flutter_local_notifications: ^9.4.0
  adjust_sdk: ^4.29.2
  flutter_staggered_grid_view: ^0.4.0
  get_it: ^7.2.0
  http: ^0.13.3
  image_picker: ^0.8.3+1
  lint: ^1.5.3
  package_info: ^2.0.2
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  provider: ^5.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  flutter_point_tab_bar: ^0.2.0
  flutter_svg: ^0.22.0
  introduction_screen: ^2.1.0
  timeago: ^3.1.0
  flutter_easyloading: ^3.0.3
  flutter_html: ^2.1.4
  intl: ^0.17.0
  flutter_speed_dial: ^3.0.5
  file_picker: ^4.1.4
  flutter_rating_bar: ^4.0.0
  store_redirect: ^2.0.0
  in_app_review: ^2.0.3
  pull_to_refresh: ^2.0.0 
  pin_code_fields: ^7.3.0
  html_unescape: ^2.0.0
  tiengviet: ^0.5.0
  flutter_styled_toast: ^2.0.0
  email_validator: ^2.0.1
  ntp: ^2.0.0
  permission_handler: ^8.0.0+2
  glass_kit: ^2.0.1
  flutter_phone_direct_caller: ^2.1.0
  currency_text_input_formatter: ^2.1.5
  glass: ^1.0.1+1
  flutter_masked_text2: ^0.9.1
  cached_network_image: ^3.2.0
  flutter_smart_dialog: ^3.0.12
  timelines: ^0.1.0
  internet_connection_checker: ^0.0.1+3
  skeleton_loader: ^2.0.0+4
dev_dependencies:
  # flutter pub pub run dapackages:dapackages.dart ./pubspec.yaml
  dapackages: ^1.6.0
  change_app_package_name: ^1.0.0

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: "^0.9.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.jpg"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/


  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700